Algoritmo "0 ATE 10"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/02/2023
Var
// Seção de Declarações das variáveis 
cont: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
EscrevaL(" >>> CONTAGEM ATE 10 <<< ")
EscrevaL("")

Para cont <- 0 ate 10 faca
     EscrevaL(cont)
FIMPARA

Para cont <- 10 ate 0 faca
     EscrevaL(cont)

Fimalgoritmo