Algoritmo "CONTAR ATÉ 10"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/02/2023
Var
// Seção de Declarações das variáveis 
num: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

      num<-1
      repita
            EscrevaL(num)
            num<- num+1
      ate (num>10)

      EscrevaL("Fim da contagem...")

Fimalgoritmo