Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/02/2023
Var
// Seção de Declarações das variáveis 
cont, valor: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
cont <- 0

EscrevaL(" Quer contar até quanto?:")
leia(valor)
Enquanto cont < valor faca
         cont <- cont + 2
         escrevaL(cont)
FIMENQUANTO

Fimalgoritmo