Algoritmo "dobro"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/01/2023
Var
// Seção de Declarações das variáveis 
n1, dobro: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva("Informe um número: ")
leia(n1)

        dobro <- n1 *2
EscrevaL("O dobro do número é: " , dobro)
Fimalgoritmo