Algoritmo "ESTRUTURA REPETICAO ENQUANTO POR 2"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/02/2023
Var
// Seção de Declarações das variáveis 
cont: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
cont <- 0
Enquanto cont < 20 faca
         cont <- cont + 2
         escrevaL(cont)
FIMENQUANTO

EscrevaL(" fim do programa! ")

Fimalgoritmo