Algoritmo "ESTRUTURA REPETICAO ENQUANTO"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/02/2023
Var
// Seção de Declarações das variáveis 
cont: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
cont <- 1
Enquanto cont <= 10 faca
         cont <- cont + 1
         escreva(cont)
FIMENQUANTO

EscrevaL(" fim do programa! ")

Fimalgoritmo