Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/01/2023
Var
// Seção de Declarações das variáveis 

msg: caractere
nome: caracter
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
msg <- "Olá Mundo!"
Escreva(msg)

nome <- "Giovanni"
Escreva("Muito Prazer" , nome)
Fimalgoritmo