Algoritmo "VERDADEIRO OU FALSO"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/01/2023
Var
// Seção de Declarações das variáveis 
a, b, c: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
a <- 2
b <- 3
c <- 4

EscrevaL(a>b)
EscrevaL(a<b)
EscrevaL(a<>b)
EscrevaL(c=a+b)

Fimalgoritmo